"""initial auth schema

Revision ID: 93932621d04b
Revises:
Created: 2026-08-04 09:50:15.661333
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "93932621d04b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False, schema="auth"
    )
    op.create_index(
        "ix_audit_logs_action_created_at",
        "audit_logs",
        ["action", "created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False, schema="auth"
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False, schema="auth"
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False, schema="auth"
    )
    op.create_index(
        "ix_audit_logs_user_id_created_at",
        "audit_logs",
        ["user_id", "created_at"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "signing_keys",
        sa.Column("kid", sa.String(length=64), nullable=False),
        sa.Column("algorithm", sa.String(length=10), nullable=False),
        sa.Column("public_pem", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signing_keys")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_signing_keys_created_at"),
        "signing_keys",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_signing_keys_kid"), "signing_keys", ["kid"], unique=True, schema="auth"
    )
    op.create_index(
        op.f("ix_signing_keys_status"), "signing_keys", ["status"], unique=False, schema="auth"
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("avatar_url", sa.String(length=1000), nullable=True),
        sa.Column("locale", sa.String(length=16), nullable=True),
        sa.Column(
            "roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "extra_permissions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("banned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ban_reason", sa.String(length=500), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_users_created_at"), "users", ["created_at"], unique=False, schema="auth"
    )
    op.create_index(
        op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False, schema="auth"
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True, schema="auth")
    op.create_index(
        "ix_users_is_active_deleted_at",
        "users",
        ["is_active", "deleted_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_users_locked_until"), "users", ["locked_until"], unique=False, schema="auth"
    )
    op.create_table(
        "email_verification_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_email_verification_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_verification_tokens")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_email_verification_tokens_created_at"),
        "email_verification_tokens",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_email_verification_tokens_expires_at"),
        "email_verification_tokens",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_email_verification_tokens_token_hash"),
        "email_verification_tokens",
        ["token_hash"],
        unique=True,
        schema="auth",
    )
    op.create_index(
        op.f("ix_email_verification_tokens_user_id"),
        "email_verification_tokens",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        "ix_email_verification_tokens_user_id_purpose",
        "email_verification_tokens",
        ["user_id", "purpose"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_account_id", sa.String(length=191), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column(
            "profile",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_oauth_accounts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_oauth_accounts")),
        sa.UniqueConstraint(
            "provider", "provider_account_id", name="uq_oauth_accounts_provider_sub"
        ),
        schema="auth",
    )
    op.create_index(
        op.f("ix_oauth_accounts_created_at"),
        "oauth_accounts",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_oauth_accounts_email"), "oauth_accounts", ["email"], unique=False, schema="auth"
    )
    op.create_index(
        op.f("ix_oauth_accounts_user_id"),
        "oauth_accounts",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        "ix_oauth_accounts_user_id_provider",
        "oauth_accounts",
        ["user_id", "provider"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_password_reset_tokens_created_at"),
        "password_reset_tokens",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_password_reset_tokens_expires_at"),
        "password_reset_tokens",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
        schema="auth",
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "recovery_codes",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_recovery_codes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recovery_codes")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_recovery_codes_code_hash"),
        "recovery_codes",
        ["code_hash"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_recovery_codes_created_at"),
        "recovery_codes",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_recovery_codes_user_id"),
        "recovery_codes",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        "ix_recovery_codes_user_id_used_at",
        "recovery_codes",
        ["user_id", "used_at"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("device_label", sa.String(length=120), nullable=True),
        sa.Column("auth_method", sa.String(length=40), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=60), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_sessions_created_at"), "sessions", ["created_at"], unique=False, schema="auth"
    )
    op.create_index(
        op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False, schema="auth"
    )
    op.create_index(
        "ix_sessions_user_id_revoked_at",
        "sessions",
        ["user_id", "revoked_at"],
        unique=False,
        schema="auth",
    )
    op.create_table(
        "totp_secrets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("secret_encrypted", sa.Text(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_step", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_totp_secrets_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_totp_secrets")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_totp_secrets_created_at"),
        "totp_secrets",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_totp_secrets_user_id"), "totp_secrets", ["user_id"], unique=True, schema="auth"
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.String(length=60), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["auth.refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_parent_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth.sessions.id"],
            name=op.f("fk_refresh_tokens_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth.users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        schema="auth",
    )
    op.create_index(
        op.f("ix_refresh_tokens_created_at"),
        "refresh_tokens",
        ["created_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_refresh_tokens_expires_at"),
        "refresh_tokens",
        ["expires_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"),
        "refresh_tokens",
        ["family_id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        "ix_refresh_tokens_family_id_revoked_at",
        "refresh_tokens",
        ["family_id", "revoked_at"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_refresh_tokens_parent_id"),
        "refresh_tokens",
        ["parent_id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_refresh_tokens_session_id"),
        "refresh_tokens",
        ["session_id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
        schema="auth",
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"),
        "refresh_tokens",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens", schema="auth")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens", schema="auth")
    op.drop_index(op.f("ix_refresh_tokens_session_id"), table_name="refresh_tokens", schema="auth")
    op.drop_index(op.f("ix_refresh_tokens_parent_id"), table_name="refresh_tokens", schema="auth")
    op.drop_index(
        "ix_refresh_tokens_family_id_revoked_at", table_name="refresh_tokens", schema="auth"
    )
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens", schema="auth")
    op.drop_index(op.f("ix_refresh_tokens_expires_at"), table_name="refresh_tokens", schema="auth")
    op.drop_index(op.f("ix_refresh_tokens_created_at"), table_name="refresh_tokens", schema="auth")
    op.drop_table("refresh_tokens", schema="auth")
    op.drop_index(op.f("ix_totp_secrets_user_id"), table_name="totp_secrets", schema="auth")
    op.drop_index(op.f("ix_totp_secrets_created_at"), table_name="totp_secrets", schema="auth")
    op.drop_table("totp_secrets", schema="auth")
    op.drop_index("ix_sessions_user_id_revoked_at", table_name="sessions", schema="auth")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions", schema="auth")
    op.drop_index(op.f("ix_sessions_created_at"), table_name="sessions", schema="auth")
    op.drop_table("sessions", schema="auth")
    op.drop_index("ix_recovery_codes_user_id_used_at", table_name="recovery_codes", schema="auth")
    op.drop_index(op.f("ix_recovery_codes_user_id"), table_name="recovery_codes", schema="auth")
    op.drop_index(op.f("ix_recovery_codes_created_at"), table_name="recovery_codes", schema="auth")
    op.drop_index(op.f("ix_recovery_codes_code_hash"), table_name="recovery_codes", schema="auth")
    op.drop_table("recovery_codes", schema="auth")
    op.drop_index(
        op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens", schema="auth"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_token_hash"),
        table_name="password_reset_tokens",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_expires_at"),
        table_name="password_reset_tokens",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_created_at"),
        table_name="password_reset_tokens",
        schema="auth",
    )
    op.drop_table("password_reset_tokens", schema="auth")
    op.drop_index("ix_oauth_accounts_user_id_provider", table_name="oauth_accounts", schema="auth")
    op.drop_index(op.f("ix_oauth_accounts_user_id"), table_name="oauth_accounts", schema="auth")
    op.drop_index(op.f("ix_oauth_accounts_email"), table_name="oauth_accounts", schema="auth")
    op.drop_index(op.f("ix_oauth_accounts_created_at"), table_name="oauth_accounts", schema="auth")
    op.drop_table("oauth_accounts", schema="auth")
    op.drop_index(
        "ix_email_verification_tokens_user_id_purpose",
        table_name="email_verification_tokens",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_user_id"),
        table_name="email_verification_tokens",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_token_hash"),
        table_name="email_verification_tokens",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_expires_at"),
        table_name="email_verification_tokens",
        schema="auth",
    )
    op.drop_index(
        op.f("ix_email_verification_tokens_created_at"),
        table_name="email_verification_tokens",
        schema="auth",
    )
    op.drop_table("email_verification_tokens", schema="auth")
    op.drop_index(op.f("ix_users_locked_until"), table_name="users", schema="auth")
    op.drop_index("ix_users_is_active_deleted_at", table_name="users", schema="auth")
    op.drop_index(op.f("ix_users_email"), table_name="users", schema="auth")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users", schema="auth")
    op.drop_index(op.f("ix_users_created_at"), table_name="users", schema="auth")
    op.drop_table("users", schema="auth")
    op.drop_index(op.f("ix_signing_keys_status"), table_name="signing_keys", schema="auth")
    op.drop_index(op.f("ix_signing_keys_kid"), table_name="signing_keys", schema="auth")
    op.drop_index(op.f("ix_signing_keys_created_at"), table_name="signing_keys", schema="auth")
    op.drop_table("signing_keys", schema="auth")
    op.drop_index("ix_audit_logs_user_id_created_at", table_name="audit_logs", schema="auth")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs", schema="auth")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs", schema="auth")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs", schema="auth")
    op.drop_index("ix_audit_logs_action_created_at", table_name="audit_logs", schema="auth")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs", schema="auth")
    op.drop_table("audit_logs", schema="auth")
    # ### end Alembic commands ###
