"""initial notifications schema

Revision ID: d49aedb7b992
Revises:
Created: 2026-08-04 20:59:52.410570
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d49aedb7b992"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_tokens")),
        sa.UniqueConstraint("token", name="uq_device_tokens_token"),
        schema="notifications",
    )
    op.create_index(
        op.f("ix_device_tokens_created_at"),
        "device_tokens",
        ["created_at"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        op.f("ix_device_tokens_user_id"),
        "device_tokens",
        ["user_id"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        "ix_device_tokens_user_id_is_active",
        "device_tokens",
        ["user_id", "is_active"],
        unique=False,
        schema="notifications",
    )
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "sms",
                "whatsapp",
                "push",
                "in_app",
                name="notification_channel_p",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint("user_id", "category", "channel", name="uq_preferences_scope"),
        schema="notifications",
    )
    op.create_index(
        op.f("ix_notification_preferences_created_at"),
        "notification_preferences",
        ["created_at"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=False,
        schema="notifications",
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("template_key", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("action_url", sa.String(length=1000), nullable=True),
        sa.Column("icon", sa.String(length=60), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        schema="notifications",
    )
    op.create_index(
        "ix_notifications_category",
        "notifications",
        ["category"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        op.f("ix_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        "ix_notifications_user_id_created_at",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        "ix_notifications_user_id_read_at",
        "notifications",
        ["user_id", "read_at"],
        unique=False,
        schema="notifications",
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_processed_events")),
        schema="notifications",
    )
    op.create_table(
        "suppressions",
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "sms",
                "whatsapp",
                "push",
                "in_app",
                name="notification_channel_s",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("destination", sa.String(length=320), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "hard_bounce",
                "complaint",
                "unsubscribed",
                "manual",
                "invalid",
                name="suppression_reason",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("detail", sa.String(length=1000), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppressions")),
        sa.UniqueConstraint("channel", "destination", name="uq_suppressions_channel_destination"),
        schema="notifications",
    )
    op.create_index(
        op.f("ix_suppressions_created_at"),
        "suppressions",
        ["created_at"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        op.f("ix_suppressions_destination"),
        "suppressions",
        ["destination"],
        unique=False,
        schema="notifications",
    )
    op.create_table(
        "templates",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "sms",
                "whatsapp",
                "push",
                "in_app",
                name="notification_channel_t",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("subject", sa.String(length=300), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column(
            "required_variables",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_templates")),
        sa.UniqueConstraint("key", "channel", "locale", name="uq_templates_key_channel_locale"),
        schema="notifications",
    )
    op.create_index(
        "ix_templates_category", "templates", ["category"], unique=False, schema="notifications"
    )
    op.create_index(
        op.f("ix_templates_created_at"),
        "templates",
        ["created_at"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        op.f("ix_templates_key"), "templates", ["key"], unique=False, schema="notifications"
    )
    op.create_table(
        "deliveries",
        sa.Column("notification_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "sms",
                "whatsapp",
                "push",
                "in_app",
                name="notification_channel_d",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("destination", sa.String(length=320), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "sending",
                "sent",
                "delivered",
                "failed",
                "bounced",
                "skipped",
                name="delivery_status",
                native_enum=False,
                length=32,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("subject", sa.String(length=300), nullable=True),
        sa.Column("body_text", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("provider_message_id", sa.String(length=191), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_deliveries_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["notification_id"],
            ["notifications.notifications.id"],
            name=op.f("fk_deliveries_notification_id_notifications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
        sa.UniqueConstraint("provider", "provider_message_id", name="uq_deliveries_provider_ref"),
        schema="notifications",
    )
    op.create_index(
        op.f("ix_deliveries_created_at"),
        "deliveries",
        ["created_at"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        "ix_deliveries_notification_id",
        "deliveries",
        ["notification_id"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        op.f("ix_deliveries_status"), "deliveries", ["status"], unique=False, schema="notifications"
    )
    op.create_index(
        "ix_deliveries_status_next_attempt_at",
        "deliveries",
        ["status", "next_attempt_at"],
        unique=False,
        schema="notifications",
    )
    op.create_index(
        op.f("ix_deliveries_user_id"),
        "deliveries",
        ["user_id"],
        unique=False,
        schema="notifications",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliveries_user_id"), table_name="deliveries", schema="notifications")
    op.drop_index(
        "ix_deliveries_status_next_attempt_at", table_name="deliveries", schema="notifications"
    )
    op.drop_index(op.f("ix_deliveries_status"), table_name="deliveries", schema="notifications")
    op.drop_index("ix_deliveries_notification_id", table_name="deliveries", schema="notifications")
    op.drop_index(op.f("ix_deliveries_created_at"), table_name="deliveries", schema="notifications")
    op.drop_table("deliveries", schema="notifications")
    op.drop_index(op.f("ix_templates_key"), table_name="templates", schema="notifications")
    op.drop_index(op.f("ix_templates_created_at"), table_name="templates", schema="notifications")
    op.drop_index("ix_templates_category", table_name="templates", schema="notifications")
    op.drop_table("templates", schema="notifications")
    op.drop_index(
        op.f("ix_suppressions_destination"), table_name="suppressions", schema="notifications"
    )
    op.drop_index(
        op.f("ix_suppressions_created_at"), table_name="suppressions", schema="notifications"
    )
    op.drop_table("suppressions", schema="notifications")
    op.drop_table("processed_events", schema="notifications")
    op.drop_index(
        "ix_notifications_user_id_read_at", table_name="notifications", schema="notifications"
    )
    op.drop_index(
        "ix_notifications_user_id_created_at", table_name="notifications", schema="notifications"
    )
    op.drop_index(
        op.f("ix_notifications_user_id"), table_name="notifications", schema="notifications"
    )
    op.drop_index(
        op.f("ix_notifications_created_at"), table_name="notifications", schema="notifications"
    )
    op.drop_index("ix_notifications_category", table_name="notifications", schema="notifications")
    op.drop_table("notifications", schema="notifications")
    op.drop_index(
        op.f("ix_notification_preferences_user_id"),
        table_name="notification_preferences",
        schema="notifications",
    )
    op.drop_index(
        op.f("ix_notification_preferences_created_at"),
        table_name="notification_preferences",
        schema="notifications",
    )
    op.drop_table("notification_preferences", schema="notifications")
    op.drop_index(
        "ix_device_tokens_user_id_is_active", table_name="device_tokens", schema="notifications"
    )
    op.drop_index(
        op.f("ix_device_tokens_user_id"), table_name="device_tokens", schema="notifications"
    )
    op.drop_index(
        op.f("ix_device_tokens_created_at"), table_name="device_tokens", schema="notifications"
    )
    op.drop_table("device_tokens", schema="notifications")
    # ### end Alembic commands ###
