"""initial search schema

Revision ID: 0ad3fa988e58
Revises:
Created: 2026-08-04 20:29:13.148695
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0ad3fa988e58"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indexed_documents",
        sa.Column("index_name", sa.String(length=120), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("last_event_id", sa.String(length=120), nullable=True),
        sa.Column("last_event_type", sa.String(length=64), nullable=True),
        sa.Column("revision", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indexed_documents")),
        sa.UniqueConstraint(
            "index_name", "document_id", name="uq_indexed_documents_index_document"
        ),
        schema="search",
    )
    op.create_index(
        op.f("ix_indexed_documents_created_at"),
        "indexed_documents",
        ["created_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_indexed_documents_deleted_at",
        "indexed_documents",
        ["deleted_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_indexed_documents_index_name_indexed_at",
        "indexed_documents",
        ["index_name", "indexed_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_indexed_documents_last_event_id",
        "indexed_documents",
        ["last_event_id"],
        unique=False,
        schema="search",
    )
    op.create_table(
        "reindex_runs",
        sa.Column("index_name", sa.String(length=120), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default=sa.text("'queued'"), nullable=False
        ),
        sa.Column("triggered_by", sa.String(length=120), nullable=True),
        sa.Column("documents_seen", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("documents_indexed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("documents_deleted", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("documents_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reindex_runs")),
        schema="search",
    )
    op.create_index(
        op.f("ix_reindex_runs_created_at"),
        "reindex_runs",
        ["created_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_reindex_runs_index_name_started_at",
        "reindex_runs",
        ["index_name", "started_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_reindex_runs_status_started_at",
        "reindex_runs",
        ["status", "started_at"],
        unique=False,
        schema="search",
    )
    op.create_table(
        "search_queries",
        sa.Column("query_text", sa.String(length=255), nullable=False),
        sa.Column("normalized_query", sa.String(length=255), nullable=False),
        sa.Column(
            "filters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("sort", sa.String(length=32), nullable=True),
        sa.Column("result_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("has_results", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("took_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_queries")),
        schema="search",
    )
    op.create_index(
        "ix_search_queries_created_at",
        "search_queries",
        ["created_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_search_queries_has_results_created_at",
        "search_queries",
        ["has_results", "created_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_search_queries_normalized_created_at",
        "search_queries",
        ["normalized_query", "created_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_search_queries_user_id", "search_queries", ["user_id"], unique=False, schema="search"
    )
    op.create_table(
        "search_clicks",
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["query_id"],
            ["search.search_queries.id"],
            name=op.f("fk_search_clicks_query_id_search_queries"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_clicks")),
        schema="search",
    )
    op.create_index(
        "ix_search_clicks_book_id_created_at",
        "search_clicks",
        ["book_id", "created_at"],
        unique=False,
        schema="search",
    )
    op.create_index(
        "ix_search_clicks_query_id", "search_clicks", ["query_id"], unique=False, schema="search"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_search_clicks_query_id", table_name="search_clicks", schema="search")
    op.drop_index(
        "ix_search_clicks_book_id_created_at", table_name="search_clicks", schema="search"
    )
    op.drop_table("search_clicks", schema="search")
    op.drop_index("ix_search_queries_user_id", table_name="search_queries", schema="search")
    op.drop_index(
        "ix_search_queries_normalized_created_at", table_name="search_queries", schema="search"
    )
    op.drop_index(
        "ix_search_queries_has_results_created_at", table_name="search_queries", schema="search"
    )
    op.drop_index("ix_search_queries_created_at", table_name="search_queries", schema="search")
    op.drop_table("search_queries", schema="search")
    op.drop_index("ix_reindex_runs_status_started_at", table_name="reindex_runs", schema="search")
    op.drop_index(
        "ix_reindex_runs_index_name_started_at", table_name="reindex_runs", schema="search"
    )
    op.drop_index(op.f("ix_reindex_runs_created_at"), table_name="reindex_runs", schema="search")
    op.drop_table("reindex_runs", schema="search")
    op.drop_index(
        "ix_indexed_documents_last_event_id", table_name="indexed_documents", schema="search"
    )
    op.drop_index(
        "ix_indexed_documents_index_name_indexed_at",
        table_name="indexed_documents",
        schema="search",
    )
    op.drop_index(
        "ix_indexed_documents_deleted_at", table_name="indexed_documents", schema="search"
    )
    op.drop_index(
        op.f("ix_indexed_documents_created_at"), table_name="indexed_documents", schema="search"
    )
    op.drop_table("indexed_documents", schema="search")
    # ### end Alembic commands ###
