"""initial books schema

Revision ID: 41e4cd928cfb
Revises:
Created: 2026-08-04 16:15:27.026351
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "41e4cd928cfb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("avatar_key", sa.String(length=500), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column(
            "socials",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_authors")),
        sa.UniqueConstraint("slug", name=op.f("uq_authors_slug")),
        schema="books",
    )
    op.create_index(
        op.f("ix_authors_created_at"), "authors", ["created_at"], unique=False, schema="books"
    )
    op.create_index(
        op.f("ix_authors_deleted_at"), "authors", ["deleted_at"], unique=False, schema="books"
    )
    op.create_index(
        "ix_authors_is_featured_name",
        "authors",
        ["is_featured", "name"],
        unique=False,
        schema="books",
    )
    op.create_index("ix_authors_name", "authors", ["name"], unique=False, schema="books")
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon", sa.String(length=100), nullable=True),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("display_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["books.categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
        schema="books",
    )
    op.create_index(
        op.f("ix_categories_created_at"), "categories", ["created_at"], unique=False, schema="books"
    )
    op.create_index(
        op.f("ix_categories_deleted_at"), "categories", ["deleted_at"], unique=False, schema="books"
    )
    op.create_index(
        "ix_categories_is_active_display_order",
        "categories",
        ["is_active", "display_order"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_categories_parent_id_display_order",
        "categories",
        ["parent_id", "display_order"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "collections",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("cover_key", sa.String(length=500), nullable=True),
        sa.Column("item_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
        sa.UniqueConstraint("user_id", "slug", name="uq_collections_user_id_slug"),
        schema="books",
    )
    op.create_index(
        op.f("ix_collections_created_at"),
        "collections",
        ["created_at"],
        unique=False,
        schema="books",
    )
    op.create_index(
        op.f("ix_collections_deleted_at"),
        "collections",
        ["deleted_at"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_collections_is_public_created_at_id",
        "collections",
        ["is_public", "created_at", "id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_collections_user_id_created_at_id",
        "collections",
        ["user_id", "created_at", "id"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_processed_events")),
        schema="books",
    )
    op.create_index(
        op.f("ix_processed_events_processed_at"),
        "processed_events",
        ["processed_at"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "publishers",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("logo_key", sa.String(length=500), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publishers")),
        sa.UniqueConstraint("slug", name=op.f("uq_publishers_slug")),
        schema="books",
    )
    op.create_index(
        op.f("ix_publishers_created_at"), "publishers", ["created_at"], unique=False, schema="books"
    )
    op.create_index(
        op.f("ix_publishers_deleted_at"), "publishers", ["deleted_at"], unique=False, schema="books"
    )
    op.create_index("ix_publishers_name", "publishers", ["name"], unique=False, schema="books")
    op.create_table(
        "books",
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("subtitle", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("isbn10", sa.String(length=13), nullable=True),
        sa.Column("isbn13", sa.String(length=17), nullable=True),
        sa.Column("language", sa.String(length=10), server_default=sa.text("'en'"), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("publication_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "processing",
                "pending_review",
                "published",
                "unpublished",
                "rejected",
                "archived",
                name="book_status",
                native_enum=False,
                length=32,
            ),
            server_default=sa.text("'draft'"),
            nullable=False,
        ),
        sa.Column("price_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("discount_price_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default=sa.text("'INR'"), nullable=False),
        sa.Column(
            "formats",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("pdf_key", sa.String(length=500), nullable=True),
        sa.Column("epub_key", sa.String(length=500), nullable=True),
        sa.Column("mobi_key", sa.String(length=500), nullable=True),
        sa.Column("sample_key", sa.String(length=500), nullable=True),
        sa.Column("cover_key", sa.String(length=500), nullable=True),
        sa.Column("thumbnail_key", sa.String(length=500), nullable=True),
        sa.Column("meta_title", sa.String(length=255), nullable=True),
        sa.Column("meta_description", sa.String(length=500), nullable=True),
        sa.Column("og_image_key", sa.String(length=500), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column(
            "ai_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("rating_average", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("rating_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("rating_sum", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("view_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("download_count", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("publisher_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "discount_price_minor IS NULL OR discount_price_minor <= price_minor",
            name=op.f("ck_books_discount_not_above_price"),
        ),
        sa.CheckConstraint("price_minor >= 0", name=op.f("ck_books_price_minor_non_negative")),
        sa.CheckConstraint("rating_count >= 0", name=op.f("ck_books_rating_count_non_negative")),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["books.publishers.id"],
            name=op.f("fk_books_publisher_id_publishers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_books")),
        sa.UniqueConstraint("isbn10", name=op.f("uq_books_isbn10")),
        sa.UniqueConstraint("isbn13", name=op.f("uq_books_isbn13")),
        sa.UniqueConstraint("slug", name=op.f("uq_books_slug")),
        schema="books",
    )
    op.create_index(
        op.f("ix_books_created_at"), "books", ["created_at"], unique=False, schema="books"
    )
    op.create_index("ix_books_created_by", "books", ["created_by"], unique=False, schema="books")
    op.create_index(
        op.f("ix_books_deleted_at"), "books", ["deleted_at"], unique=False, schema="books"
    )
    op.create_index(
        op.f("ix_books_published_at"), "books", ["published_at"], unique=False, schema="books"
    )
    op.create_index(
        "ix_books_publisher_id", "books", ["publisher_id"], unique=False, schema="books"
    )
    op.create_index(
        "ix_books_status_created_at_id",
        "books",
        ["status", "created_at", "id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_books_status_language", "books", ["status", "language"], unique=False, schema="books"
    )
    op.create_index(
        "ix_books_status_price_minor_id",
        "books",
        ["status", "price_minor", "id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_books_status_published_at_id",
        "books",
        ["status", "published_at", "id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_books_status_rating_average_id",
        "books",
        ["status", "rating_average", "id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_books_status_view_count_id",
        "books",
        ["status", "view_count", "id"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "book_authors",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "author",
                "co_author",
                "editor",
                "translator",
                "illustrator",
                "narrator",
                name="contributor_role",
                native_enum=False,
                length=32,
            ),
            server_default=sa.text("'author'"),
            nullable=False,
        ),
        sa.Column("display_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["books.authors.id"],
            name=op.f("fk_book_authors_author_id_authors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_book_authors_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("book_id", "author_id", name=op.f("pk_book_authors")),
        schema="books",
    )
    op.create_index(
        "ix_book_authors_author_id_book_id",
        "book_authors",
        ["author_id", "book_id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        op.f("ix_book_authors_created_at"),
        "book_authors",
        ["created_at"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "book_categories",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_book_categories_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["books.categories.id"],
            name=op.f("fk_book_categories_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("book_id", "category_id", name=op.f("pk_book_categories")),
        schema="books",
    )
    op.create_index(
        "ix_book_categories_category_id_book_id",
        "book_categories",
        ["category_id", "book_id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        op.f("ix_book_categories_created_at"),
        "book_categories",
        ["created_at"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "book_versions",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("pdf_key", sa.String(length=500), nullable=True),
        sa.Column("epub_key", sa.String(length=500), nullable=True),
        sa.Column("mobi_key", sa.String(length=500), nullable=True),
        sa.Column("cover_key", sa.String(length=500), nullable=True),
        sa.Column("changelog", sa.Text(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_book_versions_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_book_versions")),
        sa.UniqueConstraint("book_id", "version", name="uq_book_versions_book_id_version"),
        schema="books",
    )
    op.create_index(
        "ix_book_versions_book_id_version",
        "book_versions",
        ["book_id", "version"],
        unique=False,
        schema="books",
    )
    op.create_index(
        op.f("ix_book_versions_created_at"),
        "book_versions",
        ["created_at"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "bookmarks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.String(length=255), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("colour", sa.String(length=16), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_bookmarks_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmarks")),
        schema="books",
    )
    op.create_index("ix_bookmarks_book_id", "bookmarks", ["book_id"], unique=False, schema="books")
    op.create_index(
        op.f("ix_bookmarks_created_at"), "bookmarks", ["created_at"], unique=False, schema="books"
    )
    op.create_index(
        "ix_bookmarks_user_id_book_id_created_at_id",
        "bookmarks",
        ["user_id", "book_id", "created_at", "id"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "collection_items",
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("display_order", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_collection_items_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["books.collections.id"],
            name=op.f("fk_collection_items_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("collection_id", "book_id", name=op.f("pk_collection_items")),
        schema="books",
    )
    op.create_index(
        "ix_collection_items_book_id", "collection_items", ["book_id"], unique=False, schema="books"
    )
    op.create_index(
        "ix_collection_items_collection_id_display_order",
        "collection_items",
        ["collection_id", "display_order"],
        unique=False,
        schema="books",
    )
    op.create_index(
        op.f("ix_collection_items_created_at"),
        "collection_items",
        ["created_at"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "entitlements",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "purchase",
                "subscription",
                "free",
                "gift",
                "admin",
                name="entitlement_source",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "external_ref", sa.String(length=255), server_default=sa.text("('')"), nullable=False
        ),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("can_read", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("can_download", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_entitlements_book_id_books"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entitlements")),
        sa.UniqueConstraint(
            "user_id",
            "book_id",
            "source",
            "external_ref",
            name="uq_entitlements_user_id_book_id_source_external_ref",
        ),
        schema="books",
    )
    op.create_index(
        "ix_entitlements_book_id", "entitlements", ["book_id"], unique=False, schema="books"
    )
    op.create_index(
        op.f("ix_entitlements_created_at"),
        "entitlements",
        ["created_at"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_entitlements_order_id", "entitlements", ["order_id"], unique=False, schema="books"
    )
    op.create_index(
        "ix_entitlements_user_id_book_id",
        "entitlements",
        ["user_id", "book_id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_entitlements_user_id_granted_at_id",
        "entitlements",
        ["user_id", "granted_at", "id"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "reading_progress",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.String(length=255), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("percent", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "total_reading_seconds", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("is_finished", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_read_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "percent >= 0 AND percent <= 100",
            name=op.f("ck_reading_progress_percent_between_0_and_100"),
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_reading_progress_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reading_progress")),
        sa.UniqueConstraint("user_id", "book_id", name="uq_reading_progress_user_id_book_id"),
        schema="books",
    )
    op.create_index(
        "ix_reading_progress_book_id", "reading_progress", ["book_id"], unique=False, schema="books"
    )
    op.create_index(
        op.f("ix_reading_progress_created_at"),
        "reading_progress",
        ["created_at"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_reading_progress_user_id_last_read_at_id",
        "reading_progress",
        ["user_id", "last_read_at", "id"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "reviews",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "verified_purchase", sa.Boolean(), server_default=sa.text("(false)"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "flagged",
                name="review_status",
                native_enum=False,
                length=32,
            ),
            server_default=sa.text("'approved'"),
            nullable=False,
        ),
        sa.Column("helpful_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("moderated_by", sa.Uuid(), nullable=True),
        sa.Column("moderated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("moderation_note", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name=op.f("ck_reviews_rating_between_1_and_5")
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_reviews_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint("book_id", "user_id", name="uq_reviews_book_id_user_id"),
        schema="books",
    )
    op.create_index(
        "ix_reviews_book_id_status_created_at_id",
        "reviews",
        ["book_id", "status", "created_at", "id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_reviews_book_id_status_helpful_count_id",
        "reviews",
        ["book_id", "status", "helpful_count", "id"],
        unique=False,
        schema="books",
    )
    op.create_index(
        op.f("ix_reviews_created_at"), "reviews", ["created_at"], unique=False, schema="books"
    )
    op.create_index(
        op.f("ix_reviews_deleted_at"), "reviews", ["deleted_at"], unique=False, schema="books"
    )
    op.create_index(
        "ix_reviews_user_id_created_at",
        "reviews",
        ["user_id", "created_at"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "wishlist",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("note", sa.String(length=1000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["books.books.id"],
            name=op.f("fk_wishlist_book_id_books"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "book_id", name=op.f("pk_wishlist")),
        schema="books",
    )
    op.create_index("ix_wishlist_book_id", "wishlist", ["book_id"], unique=False, schema="books")
    op.create_index(
        op.f("ix_wishlist_created_at"), "wishlist", ["created_at"], unique=False, schema="books"
    )
    op.create_index(
        "ix_wishlist_user_id_created_at_book_id",
        "wishlist",
        ["user_id", "created_at", "book_id"],
        unique=False,
        schema="books",
    )
    op.create_table(
        "review_votes",
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("is_helpful", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["books.reviews.id"],
            name=op.f("fk_review_votes_review_id_reviews"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("review_id", "user_id", name=op.f("pk_review_votes")),
        schema="books",
    )
    op.create_index(
        op.f("ix_review_votes_created_at"),
        "review_votes",
        ["created_at"],
        unique=False,
        schema="books",
    )
    op.create_index(
        "ix_review_votes_user_id", "review_votes", ["user_id"], unique=False, schema="books"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_votes_user_id", table_name="review_votes", schema="books")
    op.drop_index(op.f("ix_review_votes_created_at"), table_name="review_votes", schema="books")
    op.drop_table("review_votes", schema="books")
    op.drop_index("ix_wishlist_user_id_created_at_book_id", table_name="wishlist", schema="books")
    op.drop_index(op.f("ix_wishlist_created_at"), table_name="wishlist", schema="books")
    op.drop_index("ix_wishlist_book_id", table_name="wishlist", schema="books")
    op.drop_table("wishlist", schema="books")
    op.drop_index("ix_reviews_user_id_created_at", table_name="reviews", schema="books")
    op.drop_index(op.f("ix_reviews_deleted_at"), table_name="reviews", schema="books")
    op.drop_index(op.f("ix_reviews_created_at"), table_name="reviews", schema="books")
    op.drop_index(
        "ix_reviews_book_id_status_helpful_count_id", table_name="reviews", schema="books"
    )
    op.drop_index("ix_reviews_book_id_status_created_at_id", table_name="reviews", schema="books")
    op.drop_table("reviews", schema="books")
    op.drop_index(
        "ix_reading_progress_user_id_last_read_at_id", table_name="reading_progress", schema="books"
    )
    op.drop_index(
        op.f("ix_reading_progress_created_at"), table_name="reading_progress", schema="books"
    )
    op.drop_index("ix_reading_progress_book_id", table_name="reading_progress", schema="books")
    op.drop_table("reading_progress", schema="books")
    op.drop_index(
        "ix_entitlements_user_id_granted_at_id", table_name="entitlements", schema="books"
    )
    op.drop_index("ix_entitlements_user_id_book_id", table_name="entitlements", schema="books")
    op.drop_index("ix_entitlements_order_id", table_name="entitlements", schema="books")
    op.drop_index(op.f("ix_entitlements_created_at"), table_name="entitlements", schema="books")
    op.drop_index("ix_entitlements_book_id", table_name="entitlements", schema="books")
    op.drop_table("entitlements", schema="books")
    op.drop_index(
        op.f("ix_collection_items_created_at"), table_name="collection_items", schema="books"
    )
    op.drop_index(
        "ix_collection_items_collection_id_display_order",
        table_name="collection_items",
        schema="books",
    )
    op.drop_index("ix_collection_items_book_id", table_name="collection_items", schema="books")
    op.drop_table("collection_items", schema="books")
    op.drop_index(
        "ix_bookmarks_user_id_book_id_created_at_id", table_name="bookmarks", schema="books"
    )
    op.drop_index(op.f("ix_bookmarks_created_at"), table_name="bookmarks", schema="books")
    op.drop_index("ix_bookmarks_book_id", table_name="bookmarks", schema="books")
    op.drop_table("bookmarks", schema="books")
    op.drop_index(op.f("ix_book_versions_created_at"), table_name="book_versions", schema="books")
    op.drop_index("ix_book_versions_book_id_version", table_name="book_versions", schema="books")
    op.drop_table("book_versions", schema="books")
    op.drop_index(
        op.f("ix_book_categories_created_at"), table_name="book_categories", schema="books"
    )
    op.drop_index(
        "ix_book_categories_category_id_book_id", table_name="book_categories", schema="books"
    )
    op.drop_table("book_categories", schema="books")
    op.drop_index(op.f("ix_book_authors_created_at"), table_name="book_authors", schema="books")
    op.drop_index("ix_book_authors_author_id_book_id", table_name="book_authors", schema="books")
    op.drop_table("book_authors", schema="books")
    op.drop_index("ix_books_status_view_count_id", table_name="books", schema="books")
    op.drop_index("ix_books_status_rating_average_id", table_name="books", schema="books")
    op.drop_index("ix_books_status_published_at_id", table_name="books", schema="books")
    op.drop_index("ix_books_status_price_minor_id", table_name="books", schema="books")
    op.drop_index("ix_books_status_language", table_name="books", schema="books")
    op.drop_index("ix_books_status_created_at_id", table_name="books", schema="books")
    op.drop_index("ix_books_publisher_id", table_name="books", schema="books")
    op.drop_index(op.f("ix_books_published_at"), table_name="books", schema="books")
    op.drop_index(op.f("ix_books_deleted_at"), table_name="books", schema="books")
    op.drop_index("ix_books_created_by", table_name="books", schema="books")
    op.drop_index(op.f("ix_books_created_at"), table_name="books", schema="books")
    op.drop_table("books", schema="books")
    op.drop_index("ix_publishers_name", table_name="publishers", schema="books")
    op.drop_index(op.f("ix_publishers_deleted_at"), table_name="publishers", schema="books")
    op.drop_index(op.f("ix_publishers_created_at"), table_name="publishers", schema="books")
    op.drop_table("publishers", schema="books")
    op.drop_index(
        op.f("ix_processed_events_processed_at"), table_name="processed_events", schema="books"
    )
    op.drop_table("processed_events", schema="books")
    op.drop_index("ix_collections_user_id_created_at_id", table_name="collections", schema="books")
    op.drop_index(
        "ix_collections_is_public_created_at_id", table_name="collections", schema="books"
    )
    op.drop_index(op.f("ix_collections_deleted_at"), table_name="collections", schema="books")
    op.drop_index(op.f("ix_collections_created_at"), table_name="collections", schema="books")
    op.drop_table("collections", schema="books")
    op.drop_index("ix_categories_parent_id_display_order", table_name="categories", schema="books")
    op.drop_index("ix_categories_is_active_display_order", table_name="categories", schema="books")
    op.drop_index(op.f("ix_categories_deleted_at"), table_name="categories", schema="books")
    op.drop_index(op.f("ix_categories_created_at"), table_name="categories", schema="books")
    op.drop_table("categories", schema="books")
    op.drop_index("ix_authors_name", table_name="authors", schema="books")
    op.drop_index("ix_authors_is_featured_name", table_name="authors", schema="books")
    op.drop_index(op.f("ix_authors_deleted_at"), table_name="authors", schema="books")
    op.drop_index(op.f("ix_authors_created_at"), table_name="authors", schema="books")
    op.drop_table("authors", schema="books")
    # ### end Alembic commands ###
