"""initial admin schema

Revision ID: 48546b8507aa
Revises:
Created: 2026-08-05 08:06:12.814404
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "48546b8507aa"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("rollout_percent", sa.Integer(), nullable=False),
        sa.Column(
            "allowlist",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rollout_percent >= 0 AND rollout_percent <= 100",
            name=op.f("ck_feature_flags_ck_feature_flags_rollout"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
        schema="admin",
    )
    op.create_index(
        op.f("ix_feature_flags_created_at"),
        "feature_flags",
        ["created_at"],
        unique=False,
        schema="admin",
    )
    op.create_index("uq_feature_flags_key", "feature_flags", ["key"], unique=True, schema="admin")
    op.create_table(
        "flag_audits",
        sa.Column("flag_key", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column(
            "before",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "after",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_flag_audits")),
        schema="admin",
    )
    op.create_index(
        op.f("ix_flag_audits_created_at"),
        "flag_audits",
        ["created_at"],
        unique=False,
        schema="admin",
    )
    op.create_index(
        "ix_flag_audits_key_created",
        "flag_audits",
        ["flag_key", "created_at"],
        unique=False,
        schema="admin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_flag_audits_key_created", table_name="flag_audits", schema="admin")
    op.drop_index(op.f("ix_flag_audits_created_at"), table_name="flag_audits", schema="admin")
    op.drop_table("flag_audits", schema="admin")
    op.drop_index("uq_feature_flags_key", table_name="feature_flags", schema="admin")
    op.drop_index(op.f("ix_feature_flags_created_at"), table_name="feature_flags", schema="admin")
    op.drop_table("feature_flags", schema="admin")
    # ### end Alembic commands ###
