"""initial workers schema

Revision ID: 5d7040cd9054
Revises:
Created: 2026-08-05 06:46:35.662169
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5d7040cd9054"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_runs",
        sa.Column("job_name", sa.String(length=120), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "succeeded",
                "failed",
                "skipped_locked",
                "disabled",
                "timed_out",
                name="worker_run_outcome",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column(
            "detail",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("worker_id", sa.String(length=120), nullable=True),
        sa.Column("triggered_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_runs")),
        schema="workers",
    )
    op.create_index(
        op.f("ix_task_runs_created_at"), "task_runs", ["created_at"], unique=False, schema="workers"
    )
    op.create_index(
        "ix_task_runs_job_started",
        "task_runs",
        ["job_name", "started_at"],
        unique=False,
        schema="workers",
    )
    op.create_index(
        "ix_task_runs_outcome_started",
        "task_runs",
        ["outcome", "started_at"],
        unique=False,
        schema="workers",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_runs_outcome_started", table_name="task_runs", schema="workers")
    op.drop_index("ix_task_runs_job_started", table_name="task_runs", schema="workers")
    op.drop_index(op.f("ix_task_runs_created_at"), table_name="task_runs", schema="workers")
    op.drop_table("task_runs", schema="workers")
    # ### end Alembic commands ###
