"""initial payment schema

Revision ID: f23717e868dd
Revises:
Created: 2026-08-04 16:47:34.428256
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f23717e868dd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "affiliate_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("commission_bps", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("total_earned_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_paid_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_accounts")),
        schema="payment",
    )
    op.create_index(
        op.f("ix_affiliate_accounts_code"),
        "affiliate_accounts",
        ["code"],
        unique=True,
        schema="payment",
    )
    op.create_index(
        op.f("ix_affiliate_accounts_created_at"),
        "affiliate_accounts",
        ["created_at"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_affiliate_accounts_user_id"),
        "affiliate_accounts",
        ["user_id"],
        unique=True,
        schema="payment",
    )
    op.create_table(
        "coupons",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "coupon_type",
            sa.Enum("percent", "fixed", name="coupon_type", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("max_discount_minor", sa.Integer(), nullable=True),
        sa.Column("min_order_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("per_user_limit", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "applicable_book_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "applicable_category_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "usage_limit IS NULL OR usage_limit > 0",
            name=op.f("ck_coupons_coupon_usage_limit_positive"),
        ),
        sa.CheckConstraint("value >= 0", name=op.f("ck_coupons_coupon_value_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupons")),
        schema="payment",
    )
    op.create_index(op.f("ix_coupons_code"), "coupons", ["code"], unique=True, schema="payment")
    op.create_index(
        op.f("ix_coupons_created_at"), "coupons", ["created_at"], unique=False, schema="payment"
    )
    op.create_index(
        "ix_coupons_is_active_valid_until",
        "coupons",
        ["is_active", "valid_until"],
        unique=False,
        schema="payment",
    )
    op.create_table(
        "subscription_plans",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("interval", sa.String(length=16), nullable=False),
        sa.Column("trial_days", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column(
            "provider_plan_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_plans")),
        schema="payment",
    )
    op.create_index(
        op.f("ix_subscription_plans_code"),
        "subscription_plans",
        ["code"],
        unique=True,
        schema="payment",
    )
    op.create_index(
        op.f("ix_subscription_plans_created_at"),
        "subscription_plans",
        ["created_at"],
        unique=False,
        schema="payment",
    )
    op.create_table(
        "webhook_events",
        sa.Column(
            "provider",
            sa.Enum(
                "razorpay",
                "stripe",
                "manual",
                name="payment_provider_w",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("event_id", sa.String(length=191), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column("processed", sa.Boolean(), server_default=sa.text("(false)"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("provider", "event_id", name="uq_webhook_provider_event"),
        schema="payment",
    )
    op.create_index(
        op.f("ix_webhook_events_created_at"),
        "webhook_events",
        ["created_at"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_webhook_events_event_type"),
        "webhook_events",
        ["event_type"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        "ix_webhook_events_processed_created_at",
        "webhook_events",
        ["processed", "created_at"],
        unique=False,
        schema="payment",
    )
    op.create_table(
        "affiliate_conversions",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("order_total_minor", sa.Integer(), nullable=False),
        sa.Column("commission_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reversed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["payment.affiliate_accounts.id"],
            name=op.f("fk_affiliate_conversions_account_id_affiliate_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_affiliate_conversions")),
        sa.UniqueConstraint("order_id", name="uq_affiliate_conversion_order"),
        schema="payment",
    )
    op.create_index(
        "ix_affiliate_conversions_account_id_created_at",
        "affiliate_conversions",
        ["account_id", "created_at"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_affiliate_conversions_created_at"),
        "affiliate_conversions",
        ["created_at"],
        unique=False,
        schema="payment",
    )
    op.create_table(
        "orders",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "awaiting_payment",
                "paid",
                "failed",
                "cancelled",
                "refunded",
                "partially_refunded",
                name="order_status",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("subtotal_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("discount_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tax_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("refunded_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("cgst_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sgst_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("igst_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tax_percent", sa.Integer(), nullable=False),
        sa.Column("place_of_supply", sa.String(length=8), nullable=True),
        sa.Column(
            "provider",
            sa.Enum(
                "razorpay",
                "stripe",
                "manual",
                name="payment_provider",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("provider_order_id", sa.String(length=191), nullable=True),
        sa.Column("checkout_url", sa.String(length=1000), nullable=True),
        sa.Column("coupon_id", sa.Uuid(), nullable=True),
        sa.Column("coupon_code", sa.String(length=64), nullable=True),
        sa.Column("affiliate_code", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key", sa.String(length=255), nullable=True),
        sa.Column("billing_name", sa.String(length=200), nullable=True),
        sa.Column("billing_email", sa.String(length=320), nullable=True),
        sa.Column(
            "billing_address",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("discount_minor >= 0", name=op.f("ck_orders_discount_non_negative")),
        sa.CheckConstraint(
            "refunded_minor <= total_minor", name=op.f("ck_orders_refund_not_above_total")
        ),
        sa.CheckConstraint("refunded_minor >= 0", name=op.f("ck_orders_refunded_non_negative")),
        sa.CheckConstraint("subtotal_minor >= 0", name=op.f("ck_orders_subtotal_non_negative")),
        sa.CheckConstraint("tax_minor >= 0", name=op.f("ck_orders_tax_non_negative")),
        sa.CheckConstraint("total_minor >= 0", name=op.f("ck_orders_total_non_negative")),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["payment.coupons.id"],
            name=op.f("fk_orders_coupon_id_coupons"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("idempotency_key", name="uq_orders_idempotency_key"),
        schema="payment",
    )
    op.create_index(
        op.f("ix_orders_affiliate_code"),
        "orders",
        ["affiliate_code"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False, schema="payment"
    )
    op.create_index(
        op.f("ix_orders_expires_at"), "orders", ["expires_at"], unique=False, schema="payment"
    )
    op.create_index(
        op.f("ix_orders_order_number"), "orders", ["order_number"], unique=True, schema="payment"
    )
    op.create_index(
        "ix_orders_provider_order_id",
        "orders",
        ["provider_order_id"],
        unique=False,
        schema="payment",
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False, schema="payment")
    op.create_index(
        "ix_orders_status_created_at",
        "orders",
        ["status", "created_at"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False, schema="payment"
    )
    op.create_index(
        "ix_orders_user_id_created_at",
        "orders",
        ["user_id", "created_at"],
        unique=False,
        schema="payment",
    )
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "razorpay",
                "stripe",
                "manual",
                name="payment_provider_s",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_subscription_id", sa.String(length=191), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "trialing",
                "active",
                "past_due",
                "cancelled",
                "expired",
                name="subscription_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancel_at_period_end", sa.Boolean(), server_default=sa.text("(false)"), nullable=False
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["payment.subscription_plans.id"],
            name=op.f("fk_subscriptions_plan_id_subscription_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "provider", "provider_subscription_id", name="uq_subscriptions_provider_ref"
        ),
        schema="payment",
    )
    op.create_index(
        op.f("ix_subscriptions_created_at"),
        "subscriptions",
        ["created_at"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        "ix_subscriptions_status_current_period_end",
        "subscriptions",
        ["status", "current_period_end"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_subscriptions_user_id"),
        "subscriptions",
        ["user_id"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        "ix_subscriptions_user_id_status",
        "subscriptions",
        ["user_id", "status"],
        unique=False,
        schema="payment",
    )
    op.create_table(
        "coupon_redemptions",
        sa.Column("coupon_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("discount_minor", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["coupon_id"],
            ["payment.coupons.id"],
            name=op.f("fk_coupon_redemptions_coupon_id_coupons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["payment.orders.id"],
            name=op.f("fk_coupon_redemptions_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coupon_redemptions")),
        sa.UniqueConstraint("coupon_id", "order_id", name="uq_redemption_coupon_order"),
        schema="payment",
    )
    op.create_index(
        "ix_coupon_redemptions_coupon_id_user_id",
        "coupon_redemptions",
        ["coupon_id", "user_id"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_coupon_redemptions_created_at"),
        "coupon_redemptions",
        ["created_at"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_coupon_redemptions_user_id"),
        "coupon_redemptions",
        ["user_id"],
        unique=False,
        schema="payment",
    )
    op.create_table(
        "invoices",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=64), nullable=False),
        sa.Column("subtotal_minor", sa.Integer(), nullable=False),
        sa.Column("discount_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tax_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("cgst_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("sgst_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("igst_minor", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("tax_percent", sa.Integer(), nullable=False),
        sa.Column("place_of_supply", sa.String(length=8), nullable=True),
        sa.Column(
            "billing_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "line_items",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("pdf_key", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["payment.orders.id"],
            name=op.f("fk_invoices_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("invoice_number", name="uq_invoices_number"),
        schema="payment",
    )
    op.create_index(
        op.f("ix_invoices_created_at"), "invoices", ["created_at"], unique=False, schema="payment"
    )
    op.create_index(
        op.f("ix_invoices_invoice_number"),
        "invoices",
        ["invoice_number"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        "ix_invoices_order_id", "invoices", ["order_id"], unique=False, schema="payment"
    )
    op.create_index(
        "ix_invoices_user_id_issued_at",
        "invoices",
        ["user_id", "issued_at"],
        unique=False,
        schema="payment",
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_minor", sa.Integer(), nullable=False),
        sa.Column("line_total_minor", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price_minor >= 0", name=op.f("ck_order_items_unit_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["payment.orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        schema="payment",
    )
    op.create_index(
        "ix_order_items_book_id", "order_items", ["book_id"], unique=False, schema="payment"
    )
    op.create_index(
        op.f("ix_order_items_created_at"),
        "order_items",
        ["created_at"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        "ix_order_items_order_id", "order_items", ["order_id"], unique=False, schema="payment"
    )
    op.create_table(
        "payments",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "razorpay",
                "stripe",
                "manual",
                name="payment_provider_p",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_payment_id", sa.String(length=191), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "authorized",
                "captured",
                "failed",
                "refunded",
                "partially_refunded",
                "disputed",
                name="payment_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("method", sa.String(length=40), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("failure_message", sa.String(length=500), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["payment.orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("provider", "provider_payment_id", name="uq_payments_provider_ref"),
        schema="payment",
    )
    op.create_index(
        op.f("ix_payments_created_at"), "payments", ["created_at"], unique=False, schema="payment"
    )
    op.create_index(
        "ix_payments_order_id", "payments", ["order_id"], unique=False, schema="payment"
    )
    op.create_index(
        "ix_payments_status_created_at",
        "payments",
        ["status", "created_at"],
        unique=False,
        schema="payment",
    )
    op.create_index(
        op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False, schema="payment"
    )
    op.create_table(
        "refunds",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "provider",
            sa.Enum(
                "razorpay",
                "stripe",
                "manual",
                name="payment_provider_r",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider_refund_id", sa.String(length=191), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "succeeded",
                "failed",
                name="refund_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_minor > 0", name=op.f("ck_refunds_refund_amount_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["payment.orders.id"],
            name=op.f("fk_refunds_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payment.payments.id"],
            name=op.f("fk_refunds_payment_id_payments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refunds")),
        sa.UniqueConstraint("provider", "provider_refund_id", name="uq_refunds_provider_ref"),
        schema="payment",
    )
    op.create_index(
        op.f("ix_refunds_created_at"), "refunds", ["created_at"], unique=False, schema="payment"
    )
    op.create_index("ix_refunds_order_id", "refunds", ["order_id"], unique=False, schema="payment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refunds_order_id", table_name="refunds", schema="payment")
    op.drop_index(op.f("ix_refunds_created_at"), table_name="refunds", schema="payment")
    op.drop_table("refunds", schema="payment")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments", schema="payment")
    op.drop_index("ix_payments_status_created_at", table_name="payments", schema="payment")
    op.drop_index("ix_payments_order_id", table_name="payments", schema="payment")
    op.drop_index(op.f("ix_payments_created_at"), table_name="payments", schema="payment")
    op.drop_table("payments", schema="payment")
    op.drop_index("ix_order_items_order_id", table_name="order_items", schema="payment")
    op.drop_index(op.f("ix_order_items_created_at"), table_name="order_items", schema="payment")
    op.drop_index("ix_order_items_book_id", table_name="order_items", schema="payment")
    op.drop_table("order_items", schema="payment")
    op.drop_index("ix_invoices_user_id_issued_at", table_name="invoices", schema="payment")
    op.drop_index("ix_invoices_order_id", table_name="invoices", schema="payment")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices", schema="payment")
    op.drop_index(op.f("ix_invoices_created_at"), table_name="invoices", schema="payment")
    op.drop_table("invoices", schema="payment")
    op.drop_index(
        op.f("ix_coupon_redemptions_user_id"), table_name="coupon_redemptions", schema="payment"
    )
    op.drop_index(
        op.f("ix_coupon_redemptions_created_at"), table_name="coupon_redemptions", schema="payment"
    )
    op.drop_index(
        "ix_coupon_redemptions_coupon_id_user_id", table_name="coupon_redemptions", schema="payment"
    )
    op.drop_table("coupon_redemptions", schema="payment")
    op.drop_index("ix_subscriptions_user_id_status", table_name="subscriptions", schema="payment")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions", schema="payment")
    op.drop_index(
        "ix_subscriptions_status_current_period_end", table_name="subscriptions", schema="payment"
    )
    op.drop_index(op.f("ix_subscriptions_created_at"), table_name="subscriptions", schema="payment")
    op.drop_table("subscriptions", schema="payment")
    op.drop_index("ix_orders_user_id_created_at", table_name="orders", schema="payment")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders", schema="payment")
    op.drop_index("ix_orders_status_created_at", table_name="orders", schema="payment")
    op.drop_index(op.f("ix_orders_status"), table_name="orders", schema="payment")
    op.drop_index("ix_orders_provider_order_id", table_name="orders", schema="payment")
    op.drop_index(op.f("ix_orders_order_number"), table_name="orders", schema="payment")
    op.drop_index(op.f("ix_orders_expires_at"), table_name="orders", schema="payment")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders", schema="payment")
    op.drop_index(op.f("ix_orders_affiliate_code"), table_name="orders", schema="payment")
    op.drop_table("orders", schema="payment")
    op.drop_index(
        op.f("ix_affiliate_conversions_created_at"),
        table_name="affiliate_conversions",
        schema="payment",
    )
    op.drop_index(
        "ix_affiliate_conversions_account_id_created_at",
        table_name="affiliate_conversions",
        schema="payment",
    )
    op.drop_table("affiliate_conversions", schema="payment")
    op.drop_index(
        "ix_webhook_events_processed_created_at", table_name="webhook_events", schema="payment"
    )
    op.drop_index(
        op.f("ix_webhook_events_event_type"), table_name="webhook_events", schema="payment"
    )
    op.drop_index(
        op.f("ix_webhook_events_created_at"), table_name="webhook_events", schema="payment"
    )
    op.drop_table("webhook_events", schema="payment")
    op.drop_index(
        op.f("ix_subscription_plans_created_at"), table_name="subscription_plans", schema="payment"
    )
    op.drop_index(
        op.f("ix_subscription_plans_code"), table_name="subscription_plans", schema="payment"
    )
    op.drop_table("subscription_plans", schema="payment")
    op.drop_index("ix_coupons_is_active_valid_until", table_name="coupons", schema="payment")
    op.drop_index(op.f("ix_coupons_created_at"), table_name="coupons", schema="payment")
    op.drop_index(op.f("ix_coupons_code"), table_name="coupons", schema="payment")
    op.drop_table("coupons", schema="payment")
    op.drop_index(
        op.f("ix_affiliate_accounts_user_id"), table_name="affiliate_accounts", schema="payment"
    )
    op.drop_index(
        op.f("ix_affiliate_accounts_created_at"), table_name="affiliate_accounts", schema="payment"
    )
    op.drop_index(
        op.f("ix_affiliate_accounts_code"), table_name="affiliate_accounts", schema="payment"
    )
    op.drop_table("affiliate_accounts", schema="payment")
    # ### end Alembic commands ###
