"""initial automation schema

Revision ID: 33dc2ceb056b
Revises:
Created: 2026-08-05 06:17:19.800342
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "33dc2ceb056b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imports",
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "completed",
                "partial",
                "failed",
                name="automation_import_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("succeeded", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column(
            "errors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
        schema="automation",
    )
    op.create_index(
        op.f("ix_imports_created_at"), "imports", ["created_at"], unique=False, schema="automation"
    )
    op.create_index(
        "ix_imports_status_created",
        "imports",
        ["status", "created_at"],
        unique=False,
        schema="automation",
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processed_events")),
        sa.UniqueConstraint("event_id", name="uq_automation_processed_events_event_id"),
        schema="automation",
    )
    op.create_index(
        op.f("ix_processed_events_created_at"),
        "processed_events",
        ["created_at"],
        unique=False,
        schema="automation",
    )
    op.create_table(
        "automation_jobs",
        sa.Column("book_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "upload",
                "import",
                "event",
                "manual",
                "reprocess",
                name="automation_source_kind",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("source_key", sa.String(length=500), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "retrying",
                "dead_lettered",
                "cancelled",
                name="automation_job_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column(
            "current_stage",
            sa.Enum(
                "collect",
                "validate",
                "extract_metadata",
                "generate_description",
                "seo",
                "tags",
                "thumbnail",
                "convert",
                "compress",
                "watermark",
                "upload",
                "index",
                "publish",
                name="automation_stage",
                native_enum=False,
                length=48,
            ),
            nullable=True,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "options",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_by", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column("import_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attempts >= 0", name=op.f("ck_automation_jobs_ck_automation_jobs_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["automation.imports.id"],
            name=op.f("fk_automation_jobs_import_id_imports"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_jobs")),
        schema="automation",
    )
    op.create_index(
        "ix_automation_jobs_book",
        "automation_jobs",
        ["book_id", "created_at"],
        unique=False,
        schema="automation",
    )
    op.create_index(
        op.f("ix_automation_jobs_book_id"),
        "automation_jobs",
        ["book_id"],
        unique=False,
        schema="automation",
    )
    op.create_index(
        op.f("ix_automation_jobs_created_at"),
        "automation_jobs",
        ["created_at"],
        unique=False,
        schema="automation",
    )
    op.create_index(
        op.f("ix_automation_jobs_next_attempt_at"),
        "automation_jobs",
        ["next_attempt_at"],
        unique=False,
        schema="automation",
    )
    op.create_index(
        "ix_automation_jobs_queue",
        "automation_jobs",
        ["status", "priority", "created_at"],
        unique=False,
        schema="automation",
    )
    op.create_index(
        op.f("ix_automation_jobs_status"),
        "automation_jobs",
        ["status"],
        unique=False,
        schema="automation",
    )
    op.create_index(
        "ix_automation_jobs_status_created",
        "automation_jobs",
        ["status", "created_at"],
        unique=False,
        schema="automation",
    )
    op.create_index(
        "uq_automation_jobs_active_source",
        "automation_jobs",
        ["source_key"],
        unique=True,
        schema="automation",
        postgresql_where=sa.text("status IN ('queued','running','retrying')"),
        sqlite_where=sa.text("status IN ('queued','running','retrying')"),
    )
    op.create_table(
        "job_stages",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "collect",
                "validate",
                "extract_metadata",
                "generate_description",
                "seo",
                "tags",
                "thumbnail",
                "convert",
                "compress",
                "watermark",
                "upload",
                "index",
                "publish",
                name="automation_stage",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "succeeded",
                "failed",
                "skipped",
                name="automation_stage_status",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["automation.automation_jobs.id"],
            name=op.f("fk_job_stages_job_id_automation_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_stages")),
        sa.UniqueConstraint("job_id", "stage", name="uq_job_stages_job_stage"),
        schema="automation",
    )
    op.create_index(
        op.f("ix_job_stages_created_at"),
        "job_stages",
        ["created_at"],
        unique=False,
        schema="automation",
    )
    op.create_index(
        "ix_job_stages_status", "job_stages", ["status", "stage"], unique=False, schema="automation"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_stages_status", table_name="job_stages", schema="automation")
    op.drop_index(op.f("ix_job_stages_created_at"), table_name="job_stages", schema="automation")
    op.drop_table("job_stages", schema="automation")
    op.drop_index(
        "uq_automation_jobs_active_source",
        table_name="automation_jobs",
        schema="automation",
        postgresql_where=sa.text("status IN ('queued','running','retrying')"),
        sqlite_where=sa.text("status IN ('queued','running','retrying')"),
    )
    op.drop_index(
        "ix_automation_jobs_status_created", table_name="automation_jobs", schema="automation"
    )
    op.drop_index(
        op.f("ix_automation_jobs_status"), table_name="automation_jobs", schema="automation"
    )
    op.drop_index("ix_automation_jobs_queue", table_name="automation_jobs", schema="automation")
    op.drop_index(
        op.f("ix_automation_jobs_next_attempt_at"),
        table_name="automation_jobs",
        schema="automation",
    )
    op.drop_index(
        op.f("ix_automation_jobs_created_at"), table_name="automation_jobs", schema="automation"
    )
    op.drop_index(
        op.f("ix_automation_jobs_book_id"), table_name="automation_jobs", schema="automation"
    )
    op.drop_index("ix_automation_jobs_book", table_name="automation_jobs", schema="automation")
    op.drop_table("automation_jobs", schema="automation")
    op.drop_index(
        op.f("ix_processed_events_created_at"), table_name="processed_events", schema="automation"
    )
    op.drop_table("processed_events", schema="automation")
    op.drop_index("ix_imports_status_created", table_name="imports", schema="automation")
    op.drop_index(op.f("ix_imports_created_at"), table_name="imports", schema="automation")
    op.drop_table("imports", schema="automation")
    # ### end Alembic commands ###
