"""initial ai schema

Revision ID: 205c45a87288
Revises:
Created: 2026-08-05 05:53:05.153534
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "205c45a87288"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cached_results",
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "description",
                "summary",
                "seo",
                "tags",
                "categories",
                "chat",
                "recommend",
                "moderation",
                "embedding",
                name="task_kind_c",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("hits", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cached_results")),
        sa.UniqueConstraint("cache_key", name="uq_cached_results_key"),
        schema="ai",
    )
    op.create_index(
        op.f("ix_cached_results_book_id"), "cached_results", ["book_id"], unique=False, schema="ai"
    )
    op.create_index(
        op.f("ix_cached_results_created_at"),
        "cached_results",
        ["created_at"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "ix_cached_results_kind_expires_at",
        "cached_results",
        ["kind", "expires_at"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "conversations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("message_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        schema="ai",
    )
    op.create_index(
        op.f("ix_conversations_created_at"),
        "conversations",
        ["created_at"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False, schema="ai"
    )
    op.create_index(
        "ix_conversations_user_id_updated_at",
        "conversations",
        ["user_id", "updated_at"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "cost_budgets",
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("cost_usd", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("request_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_budgets")),
        sa.UniqueConstraint("day", "user_id", name="uq_cost_budgets_day_user"),
        schema="ai",
    )
    op.create_index(
        op.f("ix_cost_budgets_created_at"),
        "cost_budgets",
        ["created_at"],
        unique=False,
        schema="ai",
    )
    op.create_index("ix_cost_budgets_day", "cost_budgets", ["day"], unique=False, schema="ai")
    op.create_table(
        "generations",
        sa.Column(
            "kind",
            sa.Enum(
                "description",
                "summary",
                "seo",
                "tags",
                "categories",
                "chat",
                "recommend",
                "moderation",
                "embedding",
                name="task_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "succeeded",
                "failed",
                "blocked",
                "cached",
                name="generation_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("book_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=40), nullable=True),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "data",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cost_usd", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=True),
        sa.Column("error", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("cost_usd >= 0", name=op.f("ck_generations_cost_non_negative")),
        sa.CheckConstraint(
            "input_tokens >= 0", name=op.f("ck_generations_input_tokens_non_negative")
        ),
        sa.CheckConstraint(
            "output_tokens >= 0", name=op.f("ck_generations_output_tokens_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generations")),
        schema="ai",
    )
    op.create_index("ix_generations_book_id", "generations", ["book_id"], unique=False, schema="ai")
    op.create_index(
        op.f("ix_generations_cache_key"), "generations", ["cache_key"], unique=False, schema="ai"
    )
    op.create_index(
        op.f("ix_generations_created_at"), "generations", ["created_at"], unique=False, schema="ai"
    )
    op.create_index(
        "ix_generations_created_at_status",
        "generations",
        ["created_at", "status"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "ix_generations_kind_created_at",
        "generations",
        ["kind", "created_at"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        "ix_generations_user_id_created_at",
        "generations",
        ["user_id", "created_at"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_processed_events")),
        schema="ai",
    )
    op.create_table(
        "prompt_templates",
        sa.Column(
            "kind",
            sa.Enum(
                "description",
                "summary",
                "seo",
                "tags",
                "categories",
                "chat",
                "recommend",
                "moderation",
                "embedding",
                name="task_kind_p",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_template", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False),
        sa.Column("notes", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_templates")),
        sa.UniqueConstraint("kind", "locale", "version", name="uq_prompt_templates_scope"),
        schema="ai",
    )
    op.create_index(
        op.f("ix_prompt_templates_created_at"),
        "prompt_templates",
        ["created_at"],
        unique=False,
        schema="ai",
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", name="message_role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "sources",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai.conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        schema="ai",
    )
    op.create_index(
        "ix_messages_conversation_id_created_at",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
        schema="ai",
    )
    op.create_index(
        op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False, schema="ai"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages", schema="ai")
    op.drop_index("ix_messages_conversation_id_created_at", table_name="messages", schema="ai")
    op.drop_table("messages", schema="ai")
    op.drop_index(
        op.f("ix_prompt_templates_created_at"), table_name="prompt_templates", schema="ai"
    )
    op.drop_table("prompt_templates", schema="ai")
    op.drop_table("processed_events", schema="ai")
    op.drop_index("ix_generations_user_id_created_at", table_name="generations", schema="ai")
    op.drop_index("ix_generations_kind_created_at", table_name="generations", schema="ai")
    op.drop_index("ix_generations_created_at_status", table_name="generations", schema="ai")
    op.drop_index(op.f("ix_generations_created_at"), table_name="generations", schema="ai")
    op.drop_index(op.f("ix_generations_cache_key"), table_name="generations", schema="ai")
    op.drop_index("ix_generations_book_id", table_name="generations", schema="ai")
    op.drop_table("generations", schema="ai")
    op.drop_index("ix_cost_budgets_day", table_name="cost_budgets", schema="ai")
    op.drop_index(op.f("ix_cost_budgets_created_at"), table_name="cost_budgets", schema="ai")
    op.drop_table("cost_budgets", schema="ai")
    op.drop_index("ix_conversations_user_id_updated_at", table_name="conversations", schema="ai")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations", schema="ai")
    op.drop_index(op.f("ix_conversations_created_at"), table_name="conversations", schema="ai")
    op.drop_table("conversations", schema="ai")
    op.drop_index("ix_cached_results_kind_expires_at", table_name="cached_results", schema="ai")
    op.drop_index(op.f("ix_cached_results_created_at"), table_name="cached_results", schema="ai")
    op.drop_index(op.f("ix_cached_results_book_id"), table_name="cached_results", schema="ai")
    op.drop_table("cached_results", schema="ai")
    # ### end Alembic commands ###
